image views
Vex0on/ICC_Imgur_clone pull request #7
Opened 2023-03-27 18:36 UTC by sipmartyna

### Summary
_Provide an overview of request..._

### Details
#### **What kind of change does this PR introduce?**
- [x] feature
- [ ] bug fix
- [ ] docs update

[comment]: <> (If other just change the label name and select it using "[x]")

[comment]: <> (If it is bug fix add link to issue)
[comment]: <> (IF NOT DELETE THIS SECTION FROM PR AND CONTINUE FROM Description)
#### **Link to issue:**
_Place for your issue link..._

### Description
_Add more context to describe your changes..._

2023-03-27 21:00 UTC, MadPapa commented
Where serializer? 🐒

2023-03-27 21:04 UTC, MadPapa commented on backend/imgur/urls.py
> +    path("images/<int:pk>", views.delete_image, name="delete-image"),
ten sam endpoint na update i delete?

2023-03-27 21:06 UTC, MadPapa commented on backend/imgur/models.py
(save) nadpisywanie metod nie robimy w serializerach?🤔

2023-03-28 08:57 UTC, Vex0on requested changes

2023-03-28 08:57 UTC, Vex0on commented on backend/backend/settings.py
A nie zadziała bez podawania dozwolonego adresu hosta?

`ALLOWED_HOSTS = ["0.0.0.0"]`

Bo z tego co wiem to w dockerze mamy już dozwolone hosty

2023-03-28 08:57 UTC, Vex0on commented on backend/imgur/custom_views/Image.py
Flake8 i black nawaliły przy formatowaniu.

To można zapisać w wielu linijkach, żeby nie przekraczać długości jednej linijki (POST i PUT)

Twoje:
`return Response({"message": "HTTP_422_UNPROCESSABLE_ENTITY"}, status=status.HTTP_422_UNPROCESSABLE_ENTITY)`

Poprawione:
```py
return Response(
        {"message": "HTTP_422_UNPROCESSABLE_ENTITY"},
        status=status.HTTP_422_UNPROCESSABLE_ENTITY,
    )
```

Do usunięcia nadmiarowe linijki na końcu kodu. W Pythonie zostawiamy tylko jedną na koniec

2023-03-28 08:57 UTC, Vex0on commented on backend/imgur/custom_views/Post.py
Tutaj za to brak newline na końcu kodu. Dodaj jedną i będzie git (Python black)

2023-03-28 08:57 UTC, Vex0on commented on backend/imgur/models.py
Za dużo o jedną linijkę przerwy między save, a klasą Comment (Python Black)

2023-03-28 09:00 UTC, Vex0on commented
> ### Summary
> _Provide an overview of request..._
> 
> ### Details
> #### **What kind of change does this PR introduce?**
> * [x]  feature
> * [ ]  bug fix
> * [ ]  docs update
> 
> #### **Link to issue:**
> _Place for your issue link..._
> 
> ### Description
> _Add more context to describe your changes..._

A co to za pusty opis? Gdzie jakikolwiek opis wrzucanych zmian? Czemu jest zawarty link to issue, skoro to feature, a nie bug?

2023-03-28 17:20 UTC, closed without merging